<?php

namespace DoctrineORMModule\Proxy\__CG__\Compte\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Compte extends \Compte\Entity\Compte implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'codi', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'id', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'nom', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'explicacio', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'codiAlternatiu', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'tipus', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'status', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'dateCreated'];
        }

        return ['__isInitialized__', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'codi', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'id', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'nom', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'explicacio', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'codiAlternatiu', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'tipus', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'status', '' . "\0" . 'Compte\\Entity\\Compte' . "\0" . 'dateCreated'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Compte $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCodi()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodi();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodi', []);

        return parent::getCodi();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodi($codi)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodi', [$codi]);

        return parent::setCodi($codi);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setExplicacio($explicacio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExplicacio', [$explicacio]);

        return parent::setExplicacio($explicacio);
    }

    /**
     * {@inheritDoc}
     */
    public function getExplicacio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExplicacio', []);

        return parent::getExplicacio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodiAlternatiu($codiAlternatiu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodiAlternatiu', [$codiAlternatiu]);

        return parent::setCodiAlternatiu($codiAlternatiu);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodiAlternatiu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodiAlternatiu', []);

        return parent::getCodiAlternatiu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTipus($tipus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTipus', [$tipus]);

        return parent::setTipus($tipus);
    }

    /**
     * {@inheritDoc}
     */
    public function getTipus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipus', []);

        return parent::getTipus();
    }

    /**
     * {@inheritDoc}
     */
    public function getTipusAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTipusAsString', []);

        return parent::getTipusAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getStatusAsString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatusAsString', []);

        return parent::getStatusAsString();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCreated($dateCreated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCreated', [$dateCreated]);

        return parent::setDateCreated($dateCreated);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCreated', []);

        return parent::getDateCreated();
    }

}
