<?php
$this->headTitle($this->translate("Editar Compte"));

$this->mainMenu()->setActiveItemId('comptes');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Comtes'=>$this->url('comptes'),
            'Edit Compte'=>$this->url('comptes', ['action'=>'edit', 'id'=>$compte->getId()])
            ]);

$form->get('codi')->setAttributes([
    'class'=>'form-control', 
	'placeholder'=>$this->translate("5 digits")
    ]);

$form->get('nom')->setAttributes([
    'class'=>'form-control', 
	'placeholder'=>$this->translate("Nom del compte")
    ]);

$form->get('explicacio')->setAttributes([
    'class'=>'form-control', 
	'placeholder'=> $this->translate("Nom llarg"),
    ]);

$form->get('codiAlternatiu')->setAttributes([
    'class'=>'form-control', 
	'placeholder'=>$this->translate("codi curt")
    ]);

$form->get('tipus')->setAttributes([
    'class'=>'form-control', 
    ]);

$form->get('status')->setAttributes([
    'class'=>'form-control'
    ]);

$form->get('submit')
        ->setAttributes(['class'=>'btn btn-primary'])
        ->setValue($this->translate("Desar"));

$form->prepare();
?>

<h1><?= $this->translate("Editar Compte") ?> <?= $this->escapeHtml($compte->getCodi()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('codi')); ?>
            <?= $this->formElement($form->get('codi')); ?>
            <?= $this->formElementErrors($form->get('codi')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('nom')); ?>
            <?= $this->formElement($form->get('nom')); ?>
            <?= $this->formElementErrors($form->get('nom')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('explicacio')); ?>
            <?= $this->formElement($form->get('explicacio')); ?>
            <?= $this->formElementErrors($form->get('explicacio')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('codiAlternatiu')); ?>
            <?= $this->formElement($form->get('codiAlternatiu')); ?>
            <?= $this->formElementErrors($form->get('codiAlternatiu')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('tipus')); ?>
            <?= $this->formElement($form->get('tipus')); ?>
            <?= $this->formElementErrors($form->get('tipus')); ?>                  
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>                  
        </div>
        
        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   