<?php
$this->headTitle("Comptes");

$this->mainMenu()->setActiveItemId('comptes');

$this->pageBreadcrumbs()->setItems([
            $this->translate("Inici")=>$this->url('home'),
            $this->translate("Gestió de Comptes")=>$this->url('comptes', ['persona'=> $this->persona]),
            ]);

//missatge per comfirmar esborrar
$msg_delete = addslashes($this->translate("N'està segur?"));
?>

<h1><?= $this->translate("Gestió de Comptes") ?></h1>

<p>
<a class="btn btn-default" href="<?= $this->url('comptes', ['persona' => $persona, 'action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
	<?= $this->translate("Nou Compte") ?>
</a>
</p>

<table class="table table-striped">

   <tr>
        <th><?= $this->translate("CODI") ?></th>
        <th><?= $this->translate("ID") ?></th>
        <th><?= $this->translate("Nom") ?></th>
        <th><?= $this->translate("Explicació") ?></th>
        <th><?= $this->translate("Codi Alternatiu") ?></th>
        <th><?= $this->translate("Tipus") ?></th>
        <th><?= $this->translate("Estat") ?></th>        
        <th><?= $this->translate("Data creació") ?></th>        
        <th><?= $this->translate("Accions") ?></th>        
    </tr>
    
    <?php foreach ($comptes as $compte): ?>
    
    <tr>
        <td><?= $this->escapeHtml($compte->getCodi()); ?></td>
        <td><?= $this->escapeHtml($compte->getId()); ?></td>
        <td>
            <a href="<?= $this->url('comptes', ['persona'=> $persona, 'action'=>'view', 'id'=>$compte->getId()]); ?>">
                <?= $this->escapeHtml($compte->getNom()); ?>
            </a> 
        </td>
        <td><?= $this->escapeHtml($compte->getExplicacio()); ?></td>
        <td><?= $this->escapeHtml($compte->getCodiAlternatiu()); ?></td>
        <td><?= $this->escapeHtml($compte->getTipusAsString()); ?></td>
        <td><?= $this->escapeHtml($compte->getStatusAsString()); ?></td>
		<td><?= $this->escapeHtml($compte->getDateCreated()->format('d/m/Y')); ?></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('comptes', 
                    ['persona' =>$this->persona, 'action'=>'edit', 'id'=>$compte->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span>
				<?= $this->translate("Editar") ?>
            </a>
            <a class="btn btn-danger" href="<?= $this->url('comptes', 
                    ['persona' =>$this->persona, 'action'=>'delete', 'id'=>$compte->getId()]); ?>"
					onclick="if (confirm('<?= $msg_delete ?>')) {
						document.location = this.href; } return false;">
                <span class="glyphicon glyphicon-remove" ></span>
				<?= $this->translate("Eliminar") ?>
            </a>
        </td>    
    </tr>
        
    <?php endforeach; ?>   
    
</table>

