<?php
$this->headTitle('About');

$this->mainMenu()->setActiveItemId('about');

$this->pageBreadcrumbs()->setItems([
            $this->translate("Inici")=>$this->url('home'),
            $this->translate("Sobre")=>$this->url('about'),
            ]);
?>

<h1>About</h1>

<p>
    Application name: <?= $this->escapeHtml($appName) ?>
</p>

<p>
    Application description: <?= $this->escapeHtml($appDescription) ?>
</p>
